FROM alpine:3.6

ADD . /go-ethereum
RUN \
  apk add --update git go make gcc musl-dev linux-headers && \
  cp go-ethereum/private/boot.key ~				  && \
  cp go-ethereum/private/genesis.json  ~                          && \    
  (cd go-ethereum && make geth)                           && \
  (cd go-ethereum && make bootnode)                       && \
  cp go-ethereum/build/bin/geth /usr/local/bin/           && \
  cp go-ethereum/build/bin/bootnode /usr/local/bin/           && \
#  cp go-ethereum/private/bootnode /usr/local/bin/	&& \
  apk del git go make gcc musl-dev linux-headers          && \
#  geth init ./go-ethereum/rinkeby.json			  && \
  geth init ./go-ethereum/private/genesis.json		&& \
  rm -rf /go-ethereum && rm -rf /var/cache/apk/*	 

EXPOSE 8545
EXPOSE 30301
EXPOSE 30301/udp

#ENTRYPOINT ["geth"]
#ENTRYPOINT geth --networkid=4 --fast --cache 2048 --rpc --rpcapi="db,eth,net,web3,personal,web3,admin" --rpcaddr "0.0.0.0" --verbosity 4
ENTRYPOINT bootnode --nodekey=/root/boot.key
# CMD ["/bin/sh"]
